- hosts: 192.168.185.7
  tasks:
   - file:
          state: directory
          path: "/dvd1"
   - mount:
          src: "/dev/cdrom"
          path: "/dvd1"
          state: mounted
          fstype: "iso9660"
   - yum_repository:
          baseurl: "/dvd1/AppStream"
          name: "mydvd1"
          description: "dvd1 for pacakge"
          gpgcheck: no
   - yum_repository:
          baseurl: "/dvd1/BaseOS"
          name: "mydvd2"
          description: "dvd2 for package"
          gpgcheck: no

- hosts: 192.168.185.7
  vars:
          - document_root: "/var/www/lw"
  vars_prompt:
          - name: port
            prompt: "Enter Port No: "
            private: no
  tasks:
  - debug:
          msg: "{{ ansible_all_ipv4_addresses[0] }}"
          
  - firewalld:
          port: "{{port}}/tcp"
          permanent: yes
          state: enabled
          immediate: yes

  - package:
          name: "httpd"
          state: present
  - file:
          state: directory
          path: "{{document_root}}"
  - template:
          src: "my.conf"
          dest: "/etc/httpd/conf.d/my.conf"
    notify:
      - RestartApache
      
  
  - name: "copy file to /var/www/lw folder"
    copy:
            src: "html"
            dest: "{{document_root}}"

  - name: "start httpd service"
    service:
            name: "httpd"
            state: started
  
  handlers:
    - name: RestartApache
      service:
        name: httpd
        state: restarted
        

